#!/usr/bin/env python

import random
import string
random = random.SystemRandom()

ALPHANUMERICS = string.ascii_letters + string.digits
FULL_CHARSET = ALPHANUMERICS + string.punctuation

def generate_password(length, charset):
    """
    Generate a random string of "length" with characters from "charset"
    """

    return ''.join([random.choice(charset) for i in range(length)])

if __name__ == '__main__':
    from optparse import OptionParser
    parser = OptionParser('Generate strong passwords')
    parser.add_option("-a", "--alphanumeric",
                      action="store_true", dest="alphanumeric", default=False,
                      help="Use only alphanumeric characters")
    parser.add_option("-l", "--length", metavar="LENGTH", dest="length",
                      type="int", help="Create password of specified length")
    (options, args) = parser.parse_args()

    if options.length:
        length = options.length
    else:
        length = random.randint(14,20)

    if options.alphanumeric:
        print generate_password(length, ALPHANUMERICS)
    else:
        print generate_password(length, FULL_CHARSET)

